### ISSUE TITLE
文档单词打错了

### ISSUE THREAD

**Issue by Jack-Kunlun** [baozouai/reduce-enum-webpack-plugin#1]
![image](https://github.com/baozouai/reduce-enum-webpack-plugin/assets/47732460/1c071292-51da-4bb8-a4e3-650f4b91d8de)
⬆️

**Comment by baozouai** [comment]
> ![image](https://user-images.githubusercontent.com/47732460/246981330-1c071292-51da-4bb8-a4e3-650f4b91d8de.png) ⬆️

改好了，感谢大佬 @Jack-Kunlun

**Comment by Jack-Kunlun** [comment]
重新提了一个pr，更改文档中错误的名称，老哥可以合并下 @baozouai

**Comment by baozouai** [comment]
> 重新提了一个pr，更改文档中错误的名称，老哥可以合并下 @baozouai

已merge，谢谢
